"""add chunk embeddings

Revision ID: 3369a438d6f2
Revises: b6d8850004f5
Create Date: 2026-08-16 23:54:18.819033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import VECTOR


# revision identifiers, used by Alembic.
revision: str = '3369a438d6f2'
down_revision: Union[str, Sequence[str], None] = 'b6d8850004f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('embedding', VECTOR(dim=1536), nullable=False))
    op.create_index('ix_document_chunks_embedding_hnsw', 'document_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_document_chunks_embedding_hnsw', table_name='document_chunks')
    op.drop_column('document_chunks', 'embedding')
    # ### end Alembic commands ###
