"""add user roles

Revision ID: b890ee6c0fe5
Revises: 80b74d79c30a
Create Date: 2026-08-03 20:55:30.448933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b890ee6c0fe5'
down_revision: Union[str, Sequence[str], None] = '80b74d79c30a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(length=20), server_default='user', nullable=False))
    op.create_check_constraint("ck_users_role", "users", "role IN ('user', 'admin')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_users_role", "users", type_="check")
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
